package main;

public enum State {
	GO_TO_MIDDLE, ROTATE_ON_BLACK_LINE, ROTATE_360, FOUND_OBJECT, FOUND_OBSTACLE, 
	FOUND_BALL, INITIAL, OFFENSE, BALL_IN_POSSESSION, STOPPED_IN_FRONT_OF_OBJECT, GO_TO_OBJECT,
	ROTATE
}
